name: test

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v4

      - name: Configurar JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Construir o projeto com Maven
        run: mvn clean package

      - name: Publicar para o Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: micronautas
          package: target/*.jar
